#!/bin/bash
# This file is the git hook used on the release server to assemble the zip and json files.

working_zip_directory=/home/git/
git_path=/home/git/tailwind10f
output_path=/var/www/html/plugins

GIT_WORK_TREE=$git_path git checkout -f

(
 cd $working_zip_directory &&
 zip --exclude tailwind10f/.git tailwind10f/.gitignore tailwind10f/post-receive tailwind10f/README.md -r tailwind10f.zip tailwind10f/ &&
 mv -f tailwind10f.zip $output_path/tailwind10f.zip
)

version=$(grep -e 'Version:' $git_path/tailwind10f.php | sed 's/.*Version:\s\+\([\d\.]*\)/\1/')

cat > $output_path/plugins-info.json <<EOD
{
  "tailwind10f/tailwind10f.php":{
      "version":"$version",
      "package":"https://api.10fdesign.io/plugins/tailwind10f.zip"
  }
}
EOD
cat $output_path/plugins-info.json
